-- ============================================================================
-- Easy Gold BTL - lock the exposed credentials AND keep login working
-- ============================================================================
-- Run this ONCE:
--   Supabase Dashboard -> SQL Editor -> New query -> paste me -> Run
--   ...then copy the grid that section 5 prints, and close the tab.
--
-- WHY THIS EXISTS
--   The app ships the Supabase anon key inside its JavaScript bundle, so anyone
--   who opens the site can call the REST API directly. Because
--   supabase_schema.sql never enables RLS, the `anon` role can read EVERY column
--   of the `users` table - including the plaintext `password` and the session
--   `token`. One unauthenticated GET returned every credential:
--       GET /rest/v1/users?select=*
--   This script closes exactly that hole and nothing else:
--     * generates a fresh strong password for every account that does not
--       already have one produced by this script (nothing to invent by hand),
--     * removes the anon role's ability to read users.password / users.token,
--     * moves the login check into a `security definer` function, so the app can
--       still authenticate even though it can no longer read those columns.
--
-- IMPORTANT: this file contains NO real passwords, so it stays safe in git.
--   The passwords are generated by Postgres while you run it and appear only in
--   section 5, only inside your SQL Editor session.
--
-- SAFE TO RE-RUN
--   Section 4 only touches accounts whose password does not already look like
--   'EG-XXXXXXXXXX!', so a second run changes nothing and simply prints the
--   current passwords again.
--   CAVEAT: a password you typed by hand for a NEW user (User Setting screen)
--   does not match that shape, so re-running this file would rotate it. If you
--   only want to read the current passwords back, run section 5 by itself.
--
-- Supersedes supabase_rotate_credentials.sql (that file still works, but it
-- makes you invent six passwords by hand and does not lock the columns).
-- ============================================================================

-- 0. Preflight: make sure the column the app expects really exists -----------
-- No-op when the column is already there.
alter table public.users add column if not exists is_active boolean default true;

-- 1. Who exists right now (no secrets printed at this point) ------------------
select username, name, role, team,
       length(password) as pw_length,
       (token is not null) as has_token
from public.users
order by role desc, username;

-- 2. The login RPC -----------------------------------------------------------
-- `security definer` means the body runs as the function's owner (postgres),
-- which owns the table and therefore ignores the column grant removed in
-- section 3. `set search_path` pinning is what stops a caller from re-pointing
-- the unqualified names inside the body at a table they control.
create or replace function public.verify_login(p_username text, p_password text)
returns table (username text, name text, role text, team text, is_active boolean)
language sql
security definer
set search_path = public, pg_temp
stable
as $$
  select u.username, u.name, u.role, u.team, u.is_active
    from public.users u
   where u.username = p_username
     and u.password = p_password
   limit 1;
$$;

-- PostgREST only calls a function the caller is allowed to EXECUTE.
grant execute on function public.verify_login(text, text) to anon, authenticated;

-- 3. Lock the credential columns ---------------------------------------------
-- Note the two-step shape. Supabase hands the anon role a TABLE-WIDE `grant all`
-- on every table it creates, and in Postgres a table-level grant covers every
-- column - so `revoke select (password) on public.users from anon` on its own
-- would change nothing at all. The table-level SELECT has to go first, then the
-- harmless columns are handed back one by one.
revoke select on public.users from anon, authenticated;

-- The column list is rebuilt from the catalog (skipping password + token) so
-- this works whether or not this database has the `token` column.
do $$
declare
  safe_cols text;
begin
  select string_agg(quote_ident(column_name), ', ' order by ordinal_position)
    into safe_cols
    from information_schema.columns
   where table_schema = 'public'
     and table_name   = 'users'
     and column_name not in ('password', 'token');

  execute format('grant select (%s) on public.users to anon, authenticated', safe_cols);
end $$;

-- 4. Fresh passwords ---------------------------------------------------------
-- 'EG-' + 10 random hex chars + '!' = 14 characters, typeable over the phone.
-- Only accounts that do NOT already look like that are touched, which is what
-- makes this file safe to re-run.
update public.users
   set password = 'EG-'
                  || upper(substr(md5(random()::text || clock_timestamp()::text || id::text), 1, 10))
                  || '!'
 where password !~ '^EG-[0-9A-F]{10}!$';

-- 5. RESULT - the only place the new passwords ever appear --------------------
-- Copy this grid into a password manager, hand each person their own row, then
-- close the tab. Nothing here is written to git.
select username, name, role, team, is_active,
       password as password_now
from public.users
order by role desc, username;

-- 6. Verify the lock ---------------------------------------------------------
-- Expect ZERO rows. Any row below means that role can still read that column.
select grantee,
       column_name,
       string_agg(privilege_type, ', ' order by privilege_type) as privileges
from information_schema.column_privileges
where table_schema = 'public'
  and table_name   = 'users'
  and column_name in ('password', 'token')
  and grantee in ('anon', 'authenticated')
group by grantee, column_name;

-- 7. Tell PostgREST about the new function -----------------------------------
-- Without this the API can answer "Could not find the function
-- public.verify_login(p_password, p_username) in the schema cache" for a while
-- after section 2 has already created it.
notify pgrst, 'reload schema';

-- ============================================================================
-- AFTER RUNNING THIS
--   1. Copy the section 5 grid into a password manager, then give each person
--      their own row. Do not post passwords in a group chat.
--   2. Prove the lock from a NORMAL terminal - not from this SQL Editor, which
--      always runs as the table owner and so bypasses these grants:
--        curl -s -o /dev/null -w '%{http_code}\n' \
--          "$SUPABASE_URL/rest/v1/users?select=password&limit=1" \
--          -H "apikey: $ANON_KEY"
--      Expect 401/403 ("permission denied for column password"), not 200.
--   3. Sign in to the app once with one of the section 5 passwords, on each
--      role you use (admin + staff), to confirm verify_login resolves.
--
-- WHAT THIS DOES *NOT* FIX (deliberately left out of scope for now)
--   * RLS is still OFF on submissions / checkins / merch / route_plan / users.
--     The anon key can therefore still read and write the business data (sales
--     figures, GPS, staff names) and can still UPDATE users.password, i.e. an
--     attacker holding the anon key could change an account's password although
--     they can no longer read one. Enabling UPDATE would need the app's User
--     Setting screen and Cost Manager writes to move onto RPCs with policies.
--   * Locking those tables is the next step: see DEPLOYMENT.md -> "RLS".
-- ============================================================================
